name: jest
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - develop

jobs:
  jest:
    runs-on: ubuntu-latest
    env:
      RESAS_API_KEY: ${{ secrets.RESAS_API_KEY }}

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - uses: actions/checkout@v2
      - run: |
          yarn
          yarn test
